version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-server
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_app
      - MYSQL_ROOT_PASSWORD=root    
    networks:
      - db

  node:
    build:
      context: ./node-app
      dockerfile: Dockerfile.prod
    tty: true 
    container_name: node-app
    entrypoint: wait-for mysql-server:3306 -t 40 -- node index.js
    depends_on:
      - "db"
    networks:
      - db
      - app

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: web-server
    tty: true
    depends_on:
      - "node"
    networks:
      - app
    ports:
      - 8080:80

networks:
  db:
    driver: bridge
  app:
    driver: bridge