FROM node

RUN mkdir home/node-app && \
    apt update && \
    apt install -y wget netcat && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

COPY ./app ./home/node-app

WORKDIR /home/node-app

RUN npm install

ENTRYPOINT [ "node", "index.js" ]

EXPOSE 3000